spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/exam
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver